# Test1: Conv layer

In [766]:
import numpy as np
import math

np.random.seed(42)

In [767]:
A = np.random.randint(100, size=(10, 3, 4, 5))
A

array([[[[51, 92, 14, 71, 60],
         [20, 82, 86, 74, 74],
         [87, 99, 23,  2, 21],
         [52,  1, 87, 29, 37]],

        [[ 1, 63, 59, 20, 32],
         [75, 57, 21, 88, 48],
         [90, 58, 41, 91, 59],
         [79, 14, 61, 61, 46]],

        [[61, 50, 54, 63,  2],
         [50,  6, 20, 72, 38],
         [17,  3, 88, 59, 13],
         [ 8, 89, 52,  1, 83]]],


       [[[91, 59, 70, 43,  7],
         [46, 34, 77, 80, 35],
         [49,  3,  1,  5, 53],
         [ 3, 53, 92, 62, 17]],

        [[89, 43, 33, 73, 61],
         [99, 13, 94, 47, 14],
         [71, 77, 86, 61, 39],
         [84, 79, 81, 52, 23]],

        [[25, 88, 59, 40, 28],
         [14, 44, 64, 88, 70],
         [ 8, 87,  0,  7, 87],
         [62, 10, 80,  7, 34]]],


       [[[34, 32,  4, 40, 27],
         [ 6, 72, 71, 11, 33],
         [32, 47, 22, 61, 87],
         [36, 98, 43, 85, 90]],

        [[34, 64, 98, 46, 77],
         [ 2,  0,  4, 89, 13],
         [26,  8, 78, 14, 89],
         [41, 76, 50,

In [768]:
B = np.pad(A, ((0,), (0,), (1,), (1,)), 'constant', constant_values=(0,))
print(B.shape)
B

(10, 3, 6, 7)


array([[[[ 0,  0,  0, ...,  0,  0,  0],
         [ 0, 51, 92, ..., 71, 60,  0],
         [ 0, 20, 82, ..., 74, 74,  0],
         [ 0, 87, 99, ...,  2, 21,  0],
         [ 0, 52,  1, ..., 29, 37,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0,  1, 63, ..., 20, 32,  0],
         [ 0, 75, 57, ..., 88, 48,  0],
         [ 0, 90, 58, ..., 91, 59,  0],
         [ 0, 79, 14, ..., 61, 46,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        [[ 0,  0,  0, ...,  0,  0,  0],
         [ 0, 61, 50, ..., 63,  2,  0],
         [ 0, 50,  6, ..., 72, 38,  0],
         [ 0, 17,  3, ..., 59, 13,  0],
         [ 0,  8, 89, ...,  1, 83,  0],
         [ 0,  0,  0, ...,  0,  0,  0]]],


       [[[ 0,  0,  0, ...,  0,  0,  0],
         [ 0, 91, 59, ..., 43,  7,  0],
         [ 0, 46, 34, ..., 80, 35,  0],
         [ 0, 49,  3, ...,  5, 53,  0],
         [ 0,  3, 53, ..., 62, 17,  0],
         [ 0,  0,  0, ...,  0,  0,  0]],

        [[ 0,  0,  0, ...,  0,

In [769]:
filters = np.random.randint(5, size=(5, 3, 2, 2))
filters

array([[[[4, 3],
         [0, 4]],

        [[0, 2],
         [0, 0]],

        [[0, 3],
         [0, 4]]],


       [[[2, 2],
         [0, 3]],

        [[3, 4],
         [0, 2]],

        [[3, 0],
         [3, 3]]],


       [[[2, 1],
         [4, 4]],

        [[2, 3],
         [0, 3]],

        [[2, 4],
         [3, 4]]],


       [[[0, 4],
         [4, 1]],

        [[1, 1],
         [4, 2]],

        [[4, 2],
         [2, 1]]],


       [[[3, 0],
         [1, 1]],

        [[3, 0],
         [4, 4]],

        [[1, 0],
         [1, 2]]]])

In [770]:
pad = 1
stride = 1
w = (A.shape[2]-filters.shape[2]+2*pad)/stride+1
h = (A.shape[3]-filters.shape[3]+2*pad)/stride+1

if not w//1 == w or not h//1 == h:
    raise ValueError('w and h must be int')

w, h = int(w), int(h)
w, h

(5, 6)

In [771]:
n = A.shape[0]
filter_num = filters.shape[0]
filter_size_w = filters.shape[2]
filter_size_h = filters.shape[3]
C = np.zeros((n, filter_num, w, h))

for i in range(w):
    for j in range(h):
        for k in range(filter_num):
            C[:, k, i, j] = np.sum(B[:, :, i*stride: i*stride+filter_size_w, j*stride: j*stride+filter_size_h]
                            * filters[k, :, :, :], axis=(1, 2, 3))
C

array([[[[ 448.,  568.,  272.,  536.,  248.,    0.],
         [ 618., 1108., 1114., 1082.,  982.,  240.],
         [ 776.,  866., 1132., 1202.,  864.,  296.],
         [ 732., 1130., 1367.,  577.,  708.,   84.],
         [ 338.,  506.,  543.,  560.,  568.,  148.]],

        [[ 338.,  735.,  472.,  604.,  439.,    6.],
         [ 466., 1252., 1165., 1263., 1287.,  336.],
         [ 832., 1280., 1033., 1424., 1365.,  445.],
         [ 872., 1247., 1397., 1169., 1187.,  507.],
         [ 420.,  423.,  729.,  815.,  502.,  461.]],

        [[ 451., 1144.,  967.,  814.,  817.,  246.],
         [ 803., 1460., 1650., 1889., 1576.,  598.],
         [1131., 1548., 1491., 1753., 1336.,  443.],
         [ 902., 1307., 1828., 1622., 1291.,  583.],
         [ 321.,  677.,  686.,  616.,  689.,  332.]],

        [[ 114.,  598.,  906.,  574.,  616.,  372.],
         [ 547., 1458., 1202., 1495., 1548.,  604.],
         [ 539., 1632., 1313., 1304., 1438.,  546.],
         [ 690., 1276.,  878., 1458., 10

In [772]:
C.shape

(10, 5, 5, 6)

# Test2: Max Pooling layer

In [773]:
pool_size=2

w = math.ceil(C.shape[2]/pool_size)
h = math.ceil(C.shape[3]/pool_size)
w, h

(3, 3)

In [774]:
D = np.zeros((C.shape[0], C.shape[1], w, h))

for i in range(w):
    for j in range(h):
        D[:, :, i, j] = np.max(C[:, :, i*pool_size: (i+1)*pool_size, j*pool_size: (j+1)*pool_size], axis=(2, 3))

D

array([[[[1108., 1114.,  982.],
         [1130., 1367.,  864.],
         [ 506.,  560.,  568.]],

        [[1252., 1263., 1287.],
         [1280., 1424., 1365.],
         [ 423.,  815.,  502.]],

        [[1460., 1889., 1576.],
         [1548., 1828., 1336.],
         [ 677.,  686.,  689.]],

        [[1458., 1495., 1548.],
         [1632., 1458., 1438.],
         [ 307.,  883.,  425.]],

        [[ 909., 1041., 1176.],
         [1159., 1120., 1266.],
         [ 401.,  496.,  332.]]],


       [[[1203., 1347.,  819.],
         [ 872.,  954., 1223.],
         [ 363.,  890.,  447.]],

        [[1116., 1584., 1290.],
         [1182., 1552., 1210.],
         [ 866.,  999.,  427.]],

        [[1527., 2059., 1660.],
         [1525., 1766., 1505.],
         [ 628.,  939.,  464.]],

        [[1356., 1668., 1195.],
         [1132., 1397., 1189.],
         [ 643.,  728.,  239.]],

        [[1195., 1329.,  975.],
         [1275., 1282., 1108.],
         [ 323.,  599.,  349.]]],


       [[[1101.,

In [775]:
D.shape

(10, 5, 3, 3)

# Real Work

In [776]:
import numpy as np
import math

np.random.seed(42)

In [777]:
class ThreeLayerConvNet:
    """
    A three-layer convolutional network with the following architecture:

    conv - relu - 2x2 max pool - affine - relu - affine - softmax

    The network operates on minibatches of data that have shape (N, C, H, W)
    consisting of N images, each with height H and width W and with C input
    channels.
    """
        
    def __init__(self, input_dim=(3, 4, 5), filter_num=5, filter_size=2, 
                 pad=1, stride=1, pool_size=2, hidden_dim=100, num_classes=10, 
                 weight_scale=1e-3, reg=0.0, dtype=np.float32):
        self.params = {}
        self.filter_num = filter_num
        self.filter_size = filter_size
        self.pad = pad
        self.stride = stride
        self.pool_size = pool_size
        self.reg = reg
        self.dtype = dtype
        
        W1 = np.random.randn(filter_num, input_dim[0], filter_size, filter_size) * weight_scale
        b1 = np.zeros((filter_num,))
        
        feature_map_h = (input_dim[1] - filter_size + 2*pad)/stride + 1 # H2 = (H1-F+2*P)/S+1
        feature_map_w = (input_dim[2] - filter_size + 2*pad)/stride + 1 # W2 = (W1-F+2*P)/S+1
        
        if not feature_map_h//1 == feature_map_h or not feature_map_w//1 == feature_map_w: # W2, H2 should be int
            raise ValueError('feature map width and height must be int, adjust filter size, padding or stride.')
        
        self.feature_map_h, self.feature_map_w = int(feature_map_h), int(feature_map_w)
        
        self.pooled_feature_map_h = math.ceil(feature_map_h/pool_size)
        self.pooled_feature_map_w = math.ceil(feature_map_h/pool_size)
        
        W2 = np.random.randn(self.pooled_feature_map_h * self.pooled_feature_map_w * filter_num, hidden_dim) \
             * weight_scale
        b2 = np.zeros((hidden_dim,))
        
        W3 = np.random.randn(hidden_dim, num_classes) * weight_scale
        b3 = np.zeros((num_classes))
        
        self.params['W1'], self.params['b1'] = W1, b1
        self.params['W2'], self.params['b2'] = W2, b2
        self.params['W3'], self.params['b3'] = W3, b3
        
    def loss(self, X, filters, y=None):
        W1, b1 = self.params['W1'], self.params['b1']
        W2, b2 = self.params['W2'], self.params['b2']
        W3, b3 = self.params['W3'], self.params['b3']
        
        X = np.pad(X, pad_width=((0,), (0,), (self.pad,), (self.pad,)), mode='constant', constant_values=(0,))
        feature_map = np.zeros((X.shape[0], self.filter_num, self.feature_map_h, 
                                                             self.feature_map_w)) # with shape (H2, W2)
    
        # forward pass

        # conv layer:
        # todo: is there more efficient way?
        for i in range(self.feature_map_h):
            for j in range(self.feature_map_w):
                for k in range(self.filter_num):
                    feature_map[:,k,i,j] = np.sum(X[:, :, i*self.stride: i*self.stride + self.filter_size, 
                                                         j*self.stride: j*self.stride + self.filter_size]
                                                  * filters[k,:,:,:], axis=(1, 2, 3))
        feature_map += b1[None, :, None, None]
        
        # relu:
        feature_map[feature_map < 0] = 0
        
        # max pooling
        pooled_feature_map = np.zeros((X.shape[0], self.filter_num, self.pooled_feature_map_h, 
                                                                    self.pooled_feature_map_w))
        
        patch = np.ones_like(feature_map)
        mask = np.zeros_like(feature_map)
        for i in range(self.pooled_feature_map_h):
            for j in range(self.pooled_feature_map_w):
                local_max = np.max(feature_map[:, :, i*self.pool_size: (i+1)*self.pool_size, 
                                                     j*self.pool_size: (j+1)*self.pool_size], axis=(2, 3))
                pooled_feature_map[:, :, i, j] = local_max
                patch[:, :, i*self.pool_size: (i+1)*self.pool_size, j*self.pool_size: (j+1)*self.pool_size] \
                    *= local_max[:, :, None, None]
                
        indices = np.where(patch==feature_map)
        
        # first fully connected layer
        scores1 = pooled_feature_map.reshape((X.shape[0], -1))
        scores2 = scores1.dot(W2) + b2
        
        # relu
        scores2[scores2 < 0] = 0
        
        # second fully connected layer
        scores = scores2.dot(W3) + b3
        
        # softmax
        exp_scores = np.exp(scores)
        sum_exp_scores = np.sum(exp_scores, axis=1)
        
        # loss = np.sum(np.log(sum_exp_scores) - scores[range(scores.shape[0]), y])
        # loss = loss/X.shape[0]
        # loss += 0.5 * reg* (np.sum(W1*W1) + np.sum(W2*W2) + np.sum(W3*W3))
        
        # Backpropagation
        mask[indices] = np.ones_like(mask[indices])
        return mask

In [778]:
net = ThreeLayerConvNet()
net.loss(A, filters)

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 1., 1., 0., 1., 0.],
         [0., 0., 0., 0., 1., 0.],
         [0., 1., 1., 0., 0., 0.],
         [0., 1., 0., 1., 1., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 1., 0.],
         [0., 1., 0., 1., 1., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 1., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 1., 0.],
         [0., 1., 0., 0., 1., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 1., 1., 0., 1., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 1., 0.],
         [0., 1., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 1., 1., 0., 1., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 1., 1., 0., 1., 0.],
         [0., 0., 1., 0., 1., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 1., 0., 1., 0., 1.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 1., 0.],
         [0., 0., 0., 1., 1., 0.],
        

Result is the same as D. Succeed.